name: s-line
channels:
  - conda-forge
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - numpy
  - laspy
  - scipy
  - geopandas
  - matplotlib
  - scikit-image
  - networkx
  - shapely
  - geojson
  - fiona
  - pillow
  - requests
  - pip
  - pip:
      - streamlit-sortables
